# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 16:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='linked_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Linked data field in JSON', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='linked_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Linked data field in JSON', null=True),
        ),
    ]
