# Generated by Django 3.2.25 on 2025-04-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170317_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='linked_data',
            field=models.JSONField(blank=True, help_text='Linked data field in JSON', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='linked_data',
            field=models.JSONField(blank=True, help_text='Linked data field in JSON', null=True),
        ),
    ]
